<?php
/**
 * Database & Admin Setup Wizard
 * Two-step installation: Database Config → Admin User Creation
 * 
 * Works with /public_html/app/ subdirectory structure (WordPress compatible)
 * After successful setup, delete this file (setup.php)
 */

// Define APP_ROOT to work from /app/ subdirectory
define('APP_ROOT', dirname(__FILE__));

// Check if already configured
if (file_exists(APP_ROOT . '/config/.setup-complete')) {
    die('<h1>Already Configured</h1><p>This system has already been set up. If you need to reconfigure, delete the file <code>config/.setup-complete</code> and refresh this page.</p>');
}

$errors = [];
$success = false;
$step = isset($_POST['step']) ? intval($_POST['step']) : 1;
$dbConfigSaved = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    
    // Step 1: Database Configuration
    if ($step === 1) {
        $dbHost = trim($_POST['db_host'] ?? 'localhost');
        $dbUser = trim($_POST['db_user'] ?? '');
        $dbPass = trim($_POST['db_pass'] ?? '');
        $dbName = trim($_POST['db_name'] ?? '');

        // Validate inputs
        if (empty($dbUser)) $errors[] = 'Database User is required';
        if (empty($dbName)) $errors[] = 'Database Name is required';

        // Test database connection
        if (empty($errors)) {
            try {
                $pdo = new PDO(
                    "mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4",
                    $dbUser,
                    $dbPass,
                    [
                        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    ]
                );
                
                // Update database-config.php
                $configContent = "<?php
/**
 * Database Configuration
 * Generated by setup.php on " . date('Y-m-d H:i:s') . "
 * 
 * Can be overridden by environment variables:
 * DB_HOST, DB_USER, DB_PASS, DB_NAME, DB_CHARSET, DB_PORT
 */

return [
    'driver' => getenv('DB_DRIVER') ?: 'pdo',
    'host' => getenv('DB_HOST') ?: '$dbHost',
    'user' => getenv('DB_USER') ?: '$dbUser',
    'pass' => getenv('DB_PASS') ?: '$dbPass',
    'name' => getenv('DB_NAME') ?: '$dbName',
    'charset' => getenv('DB_CHARSET') ?: 'utf8mb4',
    'port' => getenv('DB_PORT') ?: 3306,
    'options' => [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::MYSQL_ATTR_INIT_COMMAND => \"SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci\"
    ]
];
";

                if (!file_put_contents(APP_ROOT . '/config/database-config.php', $configContent)) {
                    $errors[] = 'Failed to write database configuration. Check file permissions on config/ folder.';
                } else {
                    // Database config saved, move to step 2
                    $step = 2;
                    $dbConfigSaved = true;
                }
            } catch (PDOException $e) {
                $errors[] = 'Database connection failed: ' . $e->getMessage();
            }
        }
    }
    
    // Step 2: Admin User Creation
    elseif ($step === 2) {
        require_once APP_ROOT . '/config/bootstrap.php';
        
        $adminEmail = trim($_POST['admin_email'] ?? '');
        $adminPass = trim($_POST['admin_pass'] ?? '');
        $adminPassConfirm = trim($_POST['admin_pass_confirm'] ?? '');
        $siteName = trim($_POST['site_name'] ?? 'WGroos Courier');

        // Validate inputs
        if (empty($adminEmail)) $errors[] = 'Admin Email is required';
        if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) $errors[] = 'Invalid email format';
        if (strlen($adminPass) < 8) $errors[] = 'Admin Password must be at least 8 characters';
        if ($adminPass !== $adminPassConfirm) $errors[] = 'Passwords do not match';

        if (empty($errors)) {
            try {
                // Hash password
                $hashedPass = password_hash($adminPass, PASSWORD_BCRYPT);

                // Create admin user in users table
                $stmt = $DB->prepare("
                    INSERT INTO users (username, email, password, role, status, created_at) 
                    VALUES (?, ?, ?, ?, ?, NOW())
                ");
                
                $stmt->execute([
                    'admin',
                    $adminEmail,
                    $hashedPass,
                    'admin',
                    'active'
                ]);

                // Save site name to config
                $CONFIG->set('site_name', $siteName);

                // Create setup completion marker
                file_put_contents(APP_ROOT . '/config/.setup-complete', 'Setup completed on ' . date('Y-m-d H:i:s'));
                
                $success = true;
            } catch (PDOException $e) {
                $errors[] = 'Failed to create admin user: ' . $e->getMessage();
            }
        }
    }
}

?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WGroos Courier - Setup Wizard</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }
        .container {
            background: white;
            border-radius: 10px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            max-width: 550px;
            width: 100%;
            padding: 40px;
        }
        h1 {
            color: #333;
            margin-bottom: 10px;
            font-size: 28px;
        }
        .subtitle {
            color: #666;
            margin-bottom: 30px;
            font-size: 14px;
        }
        .progress {
            display: flex;
            justify-content: space-between;
            margin-bottom: 30px;
            position: relative;
        }
        .progress::before {
            content: '';
            position: absolute;
            top: 20px;
            left: 0;
            right: 0;
            height: 2px;
            background: #eee;
            z-index: 0;
        }
        .progress-step {
            flex: 1;
            text-align: center;
            position: relative;
            z-index: 1;
        }
        .progress-number {
            width: 40px;
            height: 40px;
            background: #eee;
            color: #999;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto 10px;
            font-weight: bold;
            transition: all 0.3s;
        }
        .progress-step.active .progress-number {
            background: #667eea;
            color: white;
        }
        .progress-step.completed .progress-number {
            background: #4CAF50;
            color: white;
        }
        .progress-label {
            font-size: 12px;
            color: #999;
            font-weight: 500;
        }
        .progress-step.active .progress-label {
            color: #667eea;
        }
        .alert {
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .alert-error {
            background: #fee;
            color: #c33;
            border: 1px solid #fcc;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            color: #333;
            font-weight: 500;
            margin-bottom: 8px;
            font-size: 14px;
        }
        input {
            width: 100%;
            padding: 12px;
            border: 1px solid #ddd;
            border-radius: 5px;
            font-size: 14px;
            transition: border-color 0.3s;
        }
        input:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
        }
        button {
            width: 100%;
            padding: 12px;
            background: #667eea;
            color: white;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: background 0.3s;
        }
        button:hover {
            background: #5568d3;
        }
        .help-text {
            font-size: 12px;
            color: #999;
            margin-top: 5px;
        }
        .success-box {
            background: #f0f7ff;
            border: 2px solid #4CAF50;
            padding: 30px;
            border-radius: 10px;
            text-align: center;
        }
        .success-box h2 {
            color: #4CAF50;
            margin-bottom: 15px;
        }
        .success-box p {
            color: #666;
            margin-bottom: 20px;
            font-size: 14px;
        }
        .success-box code {
            background: #f5f5f5;
            padding: 10px;
            border-radius: 5px;
            display: block;
            margin: 10px 0;
            font-family: monospace;
            word-break: break-all;
        }
        .next-steps {
            background: #fff3cd;
            border: 1px solid #ffc107;
            padding: 15px;
            border-radius: 5px;
            margin-top: 20px;
        }
        .next-steps strong {
            display: block;
            margin-bottom: 10px;
        }
        .next-steps ol {
            margin-left: 20px;
            font-size: 14px;
        }
        .next-steps li {
            margin-bottom: 8px;
        }
        h3 {
            color: #333;
            margin-bottom: 20px;
            font-size: 16px;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }
        .credentials-box {
            background: white;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
            text-align: left;
            border: 1px solid #ddd;
        }
        .credentials-box strong {
            display: block;
            margin-bottom: 10px;
        }
        .credentials-box div {
            margin-top: 5px;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
        <?php if ($success): ?>
            <div class="success-box">
                <h2>✓ Setup Complete!</h2>
                <p>Your WGroos Courier system is ready to go!</p>
                
                <div class="credentials-box">
                    <strong>Login Credentials:</strong>
                    <div>Email: <code><?php echo htmlspecialchars($adminEmail); ?></code></div>
                    <div>Password: <code>(the password you just set)</code></div>
                </div>
                
                <div class="next-steps">
                    <strong>Next Steps:</strong>
                    <ol>
                        <li><strong>Import complete database:</strong> <a href="migrations/import-sql-dump.php" target="_blank">📊 Click Here to Import 43+ Tables</a></li>
                        <li><strong>Or run basic migration:</strong> <a href="migrations/setup.php" target="_blank">⚙️ Run Basic Migration (7 tables)</a></li>
                        <li><strong>Access admin:</strong> Visit <code>https://yourdomain.com/portals/admin/</code> and login</li>
                        <li><strong>Configure payment:</strong> Set API keys in Site Management → Payment</li>
                        <li><strong>Delete setup.php</strong> from your server for security</li>
                    </ol>
                </div>
            </div>
        <?php else: ?>
            <h1>Setup Wizard</h1>
            <p class="subtitle">Configure your WGroos Courier system</p>

            <!-- Progress Indicator -->
            <div class="progress">
                <div class="progress-step <?php echo $step >= 1 ? 'active' : ''; ?>">
                    <div class="progress-number">1</div>
                    <div class="progress-label">Database</div>
                </div>
                <div class="progress-step <?php echo $step >= 2 ? 'active' : ''; ?>">
                    <div class="progress-number">2</div>
                    <div class="progress-label">Admin User</div>
                </div>
            </div>

            <?php if (!empty($errors)): ?>
                <div class="alert alert-error">
                    <strong>Setup Failed:</strong>
                    <ul style="margin-top: 10px; margin-left: 20px;">
                        <?php foreach ($errors as $error): ?>
                            <li><?php echo htmlspecialchars($error); ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>

            <form method="POST">
                <input type="hidden" name="step" value="<?php echo $step; ?>">

                <?php if ($step === 1): ?>
                    <!-- Step 1: Database Configuration -->
                    <h3>Database Configuration</h3>

                    <div class="form-group">
                        <label for="db_host">Database Host</label>
                        <input type="text" id="db_host" name="db_host" value="localhost" required>
                        <div class="help-text">Usually <code>localhost</code> on shared hosting</div>
                    </div>

                    <div class="form-group">
                        <label for="db_user">Database User</label>
                        <input type="text" id="db_user" name="db_user" required>
                        <div class="help-text">From cPanel → MySQL Databases (format: cpaneluser_dbname)</div>
                    </div>

                    <div class="form-group">
                        <label for="db_pass">Database Password</label>
                        <input type="password" id="db_pass" name="db_pass">
                        <div class="help-text">Leave blank if no password</div>
                    </div>

                    <div class="form-group">
                        <label for="db_name">Database Name</label>
                        <input type="text" id="db_name" name="db_name" required>
                        <div class="help-text">Your database name from cPanel</div>
                    </div>

                    <button type="submit">Test Connection & Continue →</button>

                <?php elseif ($step === 2): ?>
                    <!-- Step 2: Admin User Creation -->
                    <h3>Create Admin User</h3>

                    <div class="form-group">
                        <label for="site_name">Site Name</label>
                        <input type="text" id="site_name" name="site_name" value="WGroos Courier" required>
                        <div class="help-text">Your business name (displayed in emails and admin panel)</div>
                    </div>

                    <div class="form-group">
                        <label for="admin_email">Admin Email</label>
                        <input type="email" id="admin_email" name="admin_email" required>
                        <div class="help-text">For logging into admin panel</div>
                    </div>

                    <div class="form-group">
                        <label for="admin_pass">Admin Password</label>
                        <input type="password" id="admin_pass" name="admin_pass" required>
                        <div class="help-text">Minimum 8 characters. Use mix of letters, numbers, symbols</div>
                    </div>

                    <div class="form-group">
                        <label for="admin_pass_confirm">Confirm Password</label>
                        <input type="password" id="admin_pass_confirm" name="admin_pass_confirm" required>
                        <div class="help-text">Must match the password above</div>
                    </div>

                    <button type="submit">Complete Setup ✓</button>

                <?php endif; ?>
            </form>

            <?php if ($step === 1): ?>
                <div class="next-steps">
                    <strong>Getting Your Database Credentials:</strong>
                    <ol>
                        <li>Log in to cPanel</li>
                        <li>Go to <strong>MySQL Databases</strong></li>
                        <li>Create a new database</li>
                        <li>Create a database user and assign to database</li>
                        <li>Copy the credentials and paste above</li>
                        <li>Click "Test Connection & Continue"</li>
                    </ol>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</body>
</html>
